apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Feature Flag Actions

on:
  workflow_dispatch:

jobs:
  test-flags:
    steps:
      - id: enable-demo-banner
        name: Enable demo-banner flag
        uses: cloudbees-io/feature-flag-actions/enable-flag@v1
        with:
          app_id: "9902d6c2-ed48-4827-b792-06e009812ded"
          flag_id: "887fef83-701e-4477-ae4d-bc6ffc3701fe"
          env_id: "ee22090f-3994-4aa2-a22a-1949b9a5e53e"
